Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -35,8 +35,11 @@ jobs:
         with:
           version: 'latest'
 
-      - name: Configure kubectl
-        run: echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config
+      - name: Set up Kubeconfig for MicroK8s
+        run: |
+          mkdir -p $HOME/.kube
+          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config || { echo 'Error decoding base64 input'; exit 1; }
+          chmod 600 $HOME/.kube/config
 
       - name: Apply Kubernetes manifests
         run: |
